### ISSUE TITLE
改进 YouTube 视频的显示 - Improve displaying of YouTube videos

### ISSUE THREAD

**Issue by andymason** [rootknight/Miniflux-Theme-Reeder#2]
您好。感谢您创建并分享这个漂亮的 CSS 主题。

我遇到了一个关于 YouTube 视频的问题，我认为这个问题是由于 Miniflux 将 YouTube 链接转换为使用 youtube-nocookie.com 域名引起的。具体问题是，在 JavaScript 添加了 iframe 之后，占位符图像和文本仍然可见。此外，iframe 的大小也不正确。

我在您的样式表底部添加了以下 CSS，解决了我的问题，想与您分享。

此致敬礼。

Hello. Thank you for creating and sharing this beautiful CSS theme.
I encounted an issue with YouTube videos which I believe is a result of how Miniflux converts YouTube links to use the `youtube-nocookie.com` domain. The issue is the placeholder image and text are still visible after the JavaScript has added the `iframe`. Also, the `iframe` is the wrong size.

![youtube-video-before](https://github.com/rootknight/Miniflux-Theme-Reeder/assets/11013/1357d69b-a4db-4907-a19b-875ebca30f9f)

I added the following CSS to the bottom of your styles whiched fixed the problem for me, and wanted to share it with you.

![youtube-video-after](https://github.com/rootknight/Miniflux-Theme-Reeder/assets/11013/e21249e5-6afc-4e0b-81ce-7d51eb3c27c2)

Kind regards.

```css
/* Fix YouTube video embeds */
a[href*="youtube"] {
  font-size: 0;
  padding: 0;

  img {
    display: none;
  }

  iframe {
    aspect-ratio: 16/9;
  } 
}
```
